[project]
name = "project2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=7.3.0",
]
[dependency-groups]
dev = [
    "poethepoet>=0.48.0",
]
[tool.poe.tasks]
"dev:local" = "uv run --env-file .env.local python main.py"
"dev:prod"  = "uv run --env-file .env.prod python main.py"
